apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-depl
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      volumes:
        - name: postgres-db-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - name: postgres-db
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: PG_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: myapp-configmap
                key: PG_DATABASE
        volumeMounts:
          - name: postgres-db-volume
            mountPath: /var/lib/postgres
